# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:41
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(max_length=200, verbose_name='企业文化')),
                ('content2', models.CharField(max_length=200, verbose_name='企业使命')),
                ('content3', models.CharField(max_length=200, verbose_name='价值观')),
                ('content4', models.CharField(max_length=200, verbose_name='企业精神')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '企业介绍',
                'verbose_name_plural': '企业介绍',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(max_length=30, verbose_name='心全Health Box招商热线')),
                ('content2', models.CharField(max_length=30, verbose_name='产品服务热线')),
                ('content3', models.CharField(max_length=100, verbose_name='企业地址')),
                ('image', models.ImageField(upload_to='erweima/%Y/%m', verbose_name='二维码')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='shouye/%Y/%m', verbose_name='首页1')),
                ('image2', models.ImageField(upload_to='shouye/%Y/%m', verbose_name='首页2')),
                ('image3', models.ImageField(upload_to='shouye/%Y/%m', verbose_name='首页3')),
                ('image4', models.ImageField(upload_to='shouye/%Y/%m', verbose_name='首页4')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页',
                'verbose_name_plural': '首页',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='课程名')),
                ('image', models.ImageField(upload_to='kecheng/%Y/%m', verbose_name='封面')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='课程章节')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '心全课堂',
                'verbose_name_plural': '心全课堂',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '药柜', 'verbose_name_plural': '药柜'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.CharField(choices=[('yes', '显示'), ('qx', '不显示')], default='', max_length=3, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.CharField(choices=[('yes', '显示'), ('qx', '不显示')], default='', max_length=3, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=10, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='', upload_to='fengmian/%Y/%m', verbose_name='封面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='show',
            field=models.CharField(choices=[('yes', '显示'), ('qx', '不显示')], default='', max_length=3, verbose_name='首页显示'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='xinwen/%Y/%m', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='产品简介'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='chanpin/%Y/%m', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='store',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='店铺内容'),
        ),
    ]
