# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 15:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20171206_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='content4',
        ),
        migrations.AddField(
            model_name='company',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='', upload_to='qiye/%Y/%m', verbose_name='图标'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
