# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:01
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail1',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='概述'),
        ),
    ]
