# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 11:21
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XQ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='心全Health Box')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'Health Box 编辑',
                'verbose_name_plural': 'Health Box 编辑',
            },
        ),
    ]
