# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XQ', '0002_xq'),
    ]

    operations = [
        migrations.AddField(
            model_name='xq',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='编辑'),
            preserve_default=False,
        ),
    ]
