# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(max_length=30, verbose_name='心全Health Box招商热线')),
                ('content2', models.CharField(max_length=30, verbose_name='产品服务热线')),
                ('content3', models.CharField(max_length=100, verbose_name='企业地址')),
                ('image', models.ImageField(upload_to='erweima/%Y/%m', verbose_name='二维码')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
            },
        ),
    ]
