# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='theme',
            name='title1',
            field=models.CharField(default='', max_length=30, verbose_name='左侧标签'),
        ),
        migrations.AddField(
            model_name='theme',
            name='title2',
            field=models.CharField(default='', max_length=30, verbose_name='正文标签'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, upload_to='erweima/%Y/%m', verbose_name='二维码'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to='zhuti/%Y/%m', verbose_name='主题'),
        ),
    ]
