# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0006_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Goods.Kind', verbose_name='产品种类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(default='', max_length=50, verbose_name='产品种类'),
        ),
    ]
