# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0007_auto_20171211_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Goods.Kind', verbose_name='产品类别'),
            preserve_default=False,
        ),
    ]
