# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:03
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0009_auto_20171211_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('show', models.CharField(choices=[('yes', '显示'), ('qx', '不显示')], default='', max_length=3, verbose_name='首页显示')),
                ('image', models.ImageField(default='', upload_to='chanpin/%Y/%m', verbose_name='封面')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='产品简介')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '药柜',
                'verbose_name_plural': '药柜',
            },
        ),
        migrations.RenameModel(
            old_name='Kind',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='good',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Type', verbose_name='产品类别'),
        ),
    ]
