# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:20
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0010_auto_20171211_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='', max_length=100, verbose_name='产品种类')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '产品种类',
                'verbose_name_plural': '产品种类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10, verbose_name='类别')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('show', models.CharField(choices=[('yes', '显示'), ('qx', '不显示')], default='', max_length=3, verbose_name='首页显示')),
                ('image', models.ImageField(default='', upload_to='chanpin/%Y/%m', verbose_name='封面')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='产品简介')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '药柜',
                'verbose_name_plural': '药柜',
            },
        ),
        migrations.RemoveField(
            model_name='good',
            name='type',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
