# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0011_auto_20171211_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kind',
            old_name='kind',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Goods.Kind', verbose_name='类别'),
        ),
    ]
