# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0015_auto_20171211_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='theme',
            name='title1',
            field=models.CharField(default='', max_length=30, verbose_name='左侧标签'),
        ),
        migrations.AddField(
            model_name='theme',
            name='title2',
            field=models.CharField(default='', max_length=30, verbose_name='正文标签'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='chanpin/%Y/%m', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='chanpin/%Y/%m', verbose_name='轮播图1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='chanpin/%Y/%m', verbose_name='轮播图2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='chanpin/%Y/%m', verbose_name='轮播图3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='chanpin/%Y/%m', verbose_name='轮播图4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, upload_to='chanpin/%Y/%m', verbose_name='轮播图5'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to='zhuti/%Y/%m', verbose_name='主题'),
        ),
    ]
