# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 13:39
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0016_auto_20171213_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='title1',
        ),
        migrations.AddField(
            model_name='theme',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程章节'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='', upload_to='chanpin/%Y/%m', verbose_name='轮播图1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='', upload_to='chanpin/%Y/%m', verbose_name='轮播图2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default='', upload_to='chanpin/%Y/%m', verbose_name='轮播图3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default='', upload_to='chanpin/%Y/%m', verbose_name='轮播图4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, default='', upload_to='chanpin/%Y/%m', verbose_name='轮播图5'),
        ),
    ]
