# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='导航修改'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='side',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='导航修改'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabbar',
            name='record',
            field=models.CharField(default='', max_length=200, verbose_name='备案栏'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabbar',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='导航修改'),
            preserve_default=False,
        ),
    ]
