# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20171211_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabbar',
            name='bar7',
            field=models.CharField(default='', max_length=50, verbose_name='导航栏七'),
            preserve_default=False,
        ),
    ]
