# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image4',
        ),
        migrations.AddField(
            model_name='index',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='图片名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='image1',
            field=models.ImageField(upload_to='shouye/%Y/%m', verbose_name='封面'),
        ),
    ]
