# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20171208_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image1',
        ),
        migrations.AddField(
            model_name='index',
            name='image',
            field=models.ImageField(default='', upload_to='shouye/%Y/%m', verbose_name='封面'),
            preserve_default=False,
        ),
    ]
