# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_index_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='url',
            field=models.URLField(default='', max_length=100, verbose_name='链接地址'),
        ),
    ]
