# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_auto_20171212_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='shouye/%Y/%m', verbose_name='封面'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='url',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='链接地址'),
        ),
    ]
