# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_auto_20171212_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='shouye/%Y/%m', verbose_name='封面'),
        ),
    ]
